config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"
  resources :signin, only:[:index, :new]
  resources :item_details, only:[:index]
  resources :login, only:[:index]
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get :category_search
    end
  end
  resources :creditcards, only: [:index, :new, :create, :destroy]
  resources :users, only: [:index, :show, :new] do
  end
  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, :family_name, :first_name, :family_name_reading, :first_name_reading, :birth_year, :birth_month, :birth_day, presence: true
  validates :password,length: { in: 7..128} 
  has_one :address
  has_one :creditcard
  has_many :items, dependent: :destroy
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    render 'devise/registrations/create_address'
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def address_params
    params.require(:address).permit(:family_name, :first_name, :family_name_reading, :first_name_reading, :postal_code, :prefecture, :city, :address, :building_name, :phone_number)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  #def after_sign_up_path_for(resource)
  #  super(resource)
  #end

  # The path used after sign up for inactive accounts.
  #def after_inactive_sign_up_path_for(resource)
  #  super(resource)
  #end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/views/users/_credit.html.haml
.mypage__main__right-content
  .mypage__main__right-content__credit
    .mypage__main__right-content__credit__title
      クレジットカード情報入力
  .mypage__main__right-content__data
    .mypage__main__right-content__data__box
      = form_with url:creditcards_path, method: :post, class: "mypage__main__right-content__data__box__form" do |f|
        .mypage__main__right-content__data__box__form__display
          .mypage__main__right-content__data__box__form__display__name
            %label カード番号
          .mypage__main__right-content__data__box__form__display__required
            必須
        .mypage__main__right-content__data__box__form__num
          = f.text_field :number, class: "number", placeholder: "半角数字のみ" ,maxlength: "16",id: "card_number"
        .mypage__main__right-content__data__box__form__display2
          .mypage__main__right-content__data__box__form__display2__name
            %label 有効期限
          .mypage__main__right-content__data__box__form__display2__required
            必須
        .mypage__main__right-content__data__box__form__month
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          月/
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          年
          %br
          .mypage__main__right-content__data__box__form__display3
            .mypage__main__right-content__data__box__form__display3__name
              %label セキュリティコード
            .mypage__main__right-content__data__box__form__display3__required
              必須
          .mypage__main__right-content__data__box__form__code
            = f.text_field "cvc", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            #card_token
            = f.submit "追加する", id: "token_submit"

app/views/users/_left-content.html.haml
.mypage__main__left-content
  .mypage__main__left-content__nav
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to current_user do
            マイページ
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            やることリスト
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            いいね！一覧
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to new_item_path do
            出品する
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            下書き一覧
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            出品した商品-出品中
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            出品した商品-取引中
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            出品した商品-売却済み
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            購入した商品-取引中
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            購入した商品-過去の取引
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__nav__menu
      .mypage__main__left-content__nav__menu__box
        .mypage__main__left-content__nav__menu__box__name
          = link_to "#" do
            評価一覧
        .mypage__main__left-content__nav__menu__box__icon
          = icon('fas', 'angle-right')
  .mypage__main__left-content__price
    .mypage__main__left-content__price__furipei
      フリペイ
    .mypage__main__left-content__price__menu
      .mypage__main__left-content__price__menu__box
        .mypage__main__left-content__price__menu__box__name
          = link_to "#" do
            売上・振込申請
        .mypage__main__left-content__price__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__price__menu
      .mypage__main__left-content__price__menu__box
        .mypage__main__left-content__price__menu__box__name
          = link_to "#" do
            ポイント
        .mypage__main__left-content__price__menu__box__icon
          = icon('fas', 'angle-right')
  .mypage__main__left-content__list
    .mypage__main__left-content__list__configuration
      設定
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to "#" do
            プロフィール
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to "#" do
            発送元・お届け先住所変更
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to new_creditcard_path do
            クレジットカード登録
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to "#" do
            メール/パスワード
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to "#" do
            本人情報
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to "#" do
            電話番号の確認
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')
    .mypage__main__left-content__list__menu
      .mypage__main__left-content__list__menu__box
        .mypage__main__left-content__list__menu__box__name
          = link_to users_path do
            ログアウト
        .mypage__main__left-content__list__menu__box__icon
          = icon('fas', 'angle-right')

app/views/users/_log-out.html.haml
.mypage__main__right-content
  .mypage__main__right-content__log-out
    .mypage__main__right-content__log-out__box
      .mypage__main__right-content__log-out__box__title
        = link_to destroy_user_session_path, method: :delete do
          ログアウト
        

app/views/users/_right-content.html.haml
.mypage__main__right-content
  .mypage__main__right-content__user-icon
    .mypage__main__right-content__user-icon__box
      = link_to "#" do
        .mypage__main__right-content__user-icon__box__figure
          .mypage__main__right-content__user-icon__box__figure__img
            = image_tag "member_photo_noimage_thumb.png", class:"image", alt:"logo"
          .mypage__main__right-content__user-icon__box__figure__name
            = current_user.nickname
        .mypage__main__right-content__user-icon__box__number
          .mypage__main__right-content__user-icon__box__number__list
            .mypage__main__right-content__user-icon__box__number__list__evaluation
              評価 
              %span.number
                5
            .mypage__main__right-content__user-icon__box__number__list__exhibition
              出品数
              %span.number
                1
  .mypage__main__right-content__todo
    .mypage__main__right-content__todo__title
      .mypage__main__right-content__todo__title__box
        やることリスト
    .mypage__main__right-content__todo__lists
      .mypage__main__right-content__todo__lists__list
        .mypage__main__right-content__todo__lists__list__figure
          .mypage__main__right-content__todo__lists__list__figure__logo
            = image_tag "member_photo_noimage_thumb.png", class:"image", alt:"logo"
          .mypage__main__right-content__todo__lists__list__figure__title
            現在やることはありません
            .mypage__main__right-content__todo__lists__list__figure__title__box
              .mypage__main__right-content__todo__lists__list__figure__title__box__icon
              
              .mypage__main__right-content__todo__lists__list__figure__title__box__time
  .mypage__main__right-content__container
    .mypage__main__right-content__container__title
      .mypage__main__right-content__container__title__box
        購入した商品
    .mypage__main__right-content__container__tab
      .mypage__main__right-content__container__tab__menu.active
        取引中
      .mypage__main__right-content__container__tab__menu
        過去の取引
    .mypage__main__right-content__container__lists
      .mypage__main__right-content__container__lists__show.look
        .mypage__main__right-content__container__lists__show__list
          .mypage__main__right-content__container__lists__show__list__figure
            .mypage__main__right-content__container__lists__show__list__figure__logo
              = image_tag "member_photo_noimage_thumb.png", class:"image", alt:"logo"
            .mypage__main__right-content__container__lists__show__list__figure__title
              ポケモンゴー
              .mypage__main__right-content__container__lists__show__list__figure__title__box
                .mypage__main__right-content__container__lists__show__list__figure__title__box__icon
                  a
                .mypage__main__right-content__container__lists__show__list__figure__title__box__time
                  2時間前
      .mypage__main__right-content__container__lists__show
        .mypage__main__right-content__container__lists__show__list
          .mypage__main__right-content__container__lists__show__list__figure
            .mypage__main__right-content__container__lists__show__list__figure__logo
              = image_tag "member_photo_noimage_thumb.png", class:"image", alt:"logo"
            .mypage__main__right-content__container__lists__show__list__figure__title
              ポケモん
              .mypage__main__right-content__container__lists__show__list__figure__title__box
                .mypage__main__right-content__container__lists__show__list__figure__title__box__icon
                  a
                .mypage__main__right-content__container__lists__show__list__figure__title__box__time
                  2時間前

app/views/users/index.html.haml
= render "items/indexHeader"
.mypage
  .mypage__main
    = render "left-content"
    = render "log-out"
= render "items/indexFooter"

app/views/users/new.html.haml
= render "items/indexHeader"
.mypage
  .mypage__main
    = render "left-content"
    = render "credit"
= render "items/indexFooter"

app/views/users/show.html.haml
= render "items/indexHeader"
.mypage
  .mypage__main
    = render "left-content"
    = render "right-content"
= render "items/indexFooter"