config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"
  resources :signin, only:[:index, :new]
  resources :item_details, only:[:index]
  resources :login, only:[:index]
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get :category_search
    end
  end
  resources :creditcards, only: [:index, :new, :create, :destroy]
  resources :users, only: [:index, :show, :new] do
  end
  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'
  before_action :set_item, only: [:index, :pay]

  def index
    #商品/ユーザー/クレジットカードの変数設定
    @user = current_user
    @creditcard = Creditcard.find_by(user_id: current_user.id)
    @address = Address.find_by(user_id: current_user.id)

    if @creditcard.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "creditcards", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@creditcard.payjp_id)
      @creditcard_information = customer.cards.retrieve(@creditcard.card_id)
    end
  end

  def pay
    #クレジットカードと製品の変数を設定
    @creditcard = Creditcard.find_by(user_id: current_user.id)
    #Payjpの秘密鍵を取得
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    #payjp経由で支払いを実行
    charge = Payjp::Charge.create(
      amount: @item.price,
      customer: Payjp::Customer.retrieve(@creditcard.payjp_id),
      currency: 'jpy'
    )
    #製品のbuyer_idを付与
    @item_buyer= Item.find(params[:id])
    @item_buyer.update( buyer_id: current_user.id)
    redirect_to done_purchase_path
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

end

app/views/purchase/_indexBody.html.haml
.buy-main
  .buy-main__item

    .buy-main__item__header
      %h2 購入内容の確認

    .buy-main__item__image-deta
      .buy-main__item__image-deta__inner
        .buy-main__item__image-deta__inner__box
          %h3.item-image
            - @item.images.first(1).each do |item|
              = image_tag item.src.url, class:"img", alt:"buy-image"
          .item-deta
            %p.item-deta__name
              = @item.name
            %p.item-deta__text
              %span.price
                = number_to_currency(@item.price,format: "%u%n",unit:"¥",precision: 0)
              %span.fee
                （税込み)


    .buy-main__item__buyer-deta
      .buy-main__item__buyer-deta__inner
        = form_with url: pay_purchase_path do |f|
          %ul.price
            %li.price__table
              .price__table__pay
                支払い金額
              .price__table__money
                = number_to_currency(@item.price,format: "%u%n",unit:"¥",precision: 0)
              
          .point
            = check_box_tag :point_box
            = label_tag :point_tag, "ポイントを使用(所持ポイント : p)"

          .cards
            .cards__inner
              .clearfix.cards__inner__box
                %h3.left
                  支払い方法
                .right
                  = link_to new_creditcard_path do
                    変更する
              .cards__inner__text
                = "**** **** **** " + @creditcard_information.last4
              .cards__inner__logo


          .send
            .send__inner
              .clearfix.send__inner__box
                %h3.left
                  配送先
                .right
                  = link_to "#" do
                    変更する
              .send__inner__text
                〒
                = @address.postal_code
                .send__inner__text__inline
                  = @address.prefecture
                  = @address.city
                  = @address.address
                  .send__inner__text__inline2
                    = @address.family_name
                    = @address.first_name

          .buy-btn
            = f.submit '購入する', class:"buy-btn__submit", url: "pay_purchase_path", method: :post

app/views/purchase/done.html.haml
.wrapper
  = render partial: "signin/indexHeader"
  .end-new
    .end-new__main
      .end-new__main__top
        %h2 購入手続き完了
      .end-new__main__middle
        .end-new__main__middle__h
          %h2 購入が完了しました
        = link_to root_path do
          .end-new__main__middle__btn
            トップページに戻る
  
  = render partial:"signin/footer"

app/views/purchase/index.html.haml
.wrapper
  = render partial: "signin/indexHeader"
  = render partial: "indexBody"
  = render partial:"signin/footer"