config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"
  resources :signin, only:[:index, :new]
  resources :item_details, only:[:index]
  resources :login, only:[:index]
  resources :items, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get :category_search
    end
  end
  resources :creditcards, only: [:index, :new, :create, :destroy]
  resources :users, only: [:index, :show, :new] do
  end
  resources :purchase, only: [:index] do
    member do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category

  
  validates :name,                length:    {maximum: 40},                               presence: true
  validates :introduction,        length:    {maximum: 1000},                             presence: true
  validates :category_id,         exclusion: {in: %w(選択してください)},                     presence: true
  validates :trading_status,      exclusion: {in: %w(選択してください)},                     presence: true
  validates :postage_payer,       exclusion: {in: %w(選択してください)},                     presence: true
  validates :postage_type,        exclusion: {in: %w(選択してください)},                     presence: true
  validates :shipping_area,       exclusion: {in: %w(選択してください)},                     presence: true
  validates :shipping_date,       exclusion: {in: %w(選択してください)},                     presence: true
  validates :price,               length: {minimum: 3, maxinum: 7},numericality: { only_integer: true,greater_than: 299, less_than: 10000000}, presence: true

  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new(STDOUT)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, except: [:index, :new, :create, :category_search]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @item.images.new
    @parents = Category.all.order("id ASC").limit(13)
  end

  def create
    @item = Item.new(item_params)
    @parents = Category.all.order("id ASC").limit(13)
    logger.debug @item.errors.inspect
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def category_search
    respond_to do |format|
      format.html
      format.json do
        if params[:parent_id]
          @children = Category.find(params[:parent_id]).children
        else
          @grand_children = Category.find(params[:child_id]).children
        end
      end
    end
  end

  def edit
    @parents = Category.all.order("id ASC").limit(13)
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def show
    @parents = Category.where(ancestry: nil)
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :trading_status, :postage_payer, :postage_type, :shipping_area, :shipping_date, :price, :brand, :category_id, images_attributes: [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/items/_banner.html.haml
.app-banner
  .app-banner__inner
    .app-banner__inner__title
      誰でもかんたん、人生を変えるフリマアプリ
    .app-banner__inner__text
      今すぐ無料ダウンロード！
    .app-banner__inner__icon
      .app-banner__inner__icon__app
        = link_to "#" do
          = image_tag "App.svg", class:"image", alt:"logo"
      .app-banner__inner__icon__google
        = link_to "#" do
          = image_tag "google.png", class:"image", alt:"logo"

app/views/items/_crumbs.html.haml
.crumbs-container
  .crumbs
    .crumbs__link
      .crumbs__link__furima
        = link_to "#" , class: "furima-top-page" do
          フリマ
      .crumbs__link__icon
        = icon('fas', 'chevron-right')
    .crumbs__item-name
      すーぱーぷよぷよ
      .crumbs-transparent

app/views/items/_footer.html.haml
.footer
  .footer__contents
    .footer__contents__content
      .footer__contents__content__head
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要(運営会社)
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    .footer__contents__content
      .footer__contents__content__head
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    .footer__contents__content
      .footer__contents__content__head
        ヘルプ&ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .footer__logo
    = link_to "#" do
      = image_tag "logo-white.png", class:"image", alt:"logo"
  .footer__name
    ©︎ FURIMA

app/views/items/_header.html.haml
.header
  .header__inner
    .header__inner__main
      .header__inner__main__icon
        = link_to root_path do
          = image_tag "logo.png", class:"image", alt:"logo"
      .header__inner__main__search
        .header__inner__main__search__form
          = form_with url: "a", local: true, method: :get, class: "header__inner__main__search__form__input" do |form|
            .header__inner__main__search__form__input__box
              = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-input"
            .header__inner__main__search__form__btn
              = link_to "#" do
                = image_tag "icon-search 1.png", class:"image", alt:"logo"
    .header__inner__nav
      .header__inner__nav__left
        .header__inner__nav__left__category
          %ul.menu
            %li
              = link_to "#" do
                カテゴリー
              %ul.sub-menu-nav
                %li
                  = link_to "#" do
                    レディース
                    %ul
                      %li
                        = link_to "#" do
                          トップス
                          %ul
                            %li
                              = link_to "#" do
                                Tシャツ
                      %li
                        = link_to "#" do
                          ジャケット
                          %ul
                            %li
                              = link_to "#" do
                                ダウンジャケット
                      %li
                        = link_to "#" do
                          パンツ
                          %ul
                            %li
                              = link_to "#" do
                                デニム
                %li
                  = link_to "#" do
                    メンズ
                    %ul
                      %li
                        = link_to "#" do
                          トップス
                          %ul
                            %li
                              = link_to "#" do
                                Tシャツ
                      %li
                        = link_to "#" do
                          ジャケット
                          %ul
                            %li
                              = link_to "#" do
                                ダウンジャケット
                      %li
                        = link_to "#" do
                          パンツ
                          %ul
                            %li
                              = link_to "#" do
                                デニム
                %li
                  = link_to "#" do
                    ベビー・キッズ
                    %ul
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
        .header__inner__nav__left__brand
          = link_to "#" do
            ブランド
      .header__inner__nav__right
        .header__inner__nav__right__login
          = link_to "#" do
            ログイン
        .header__inner__nav__right__new
          = link_to "#" do
            新規会員登録

app/views/items/_indexBtn.html.haml
= link_to new_item_path, data: {"turbolinks" => false} do
  .exhibition-btn
    .exhibition-btn__text
      出品する
    .exhibition-btn__icon
      = image_tag "icon_camera.png", class:"image", alt:"logo"

app/views/items/_indexFooter.html.haml
.footer
  .footer__contents
    .footer__contents__content
      .footer__contents__content__head
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要(運営会社)
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    .footer__contents__content
      .footer__contents__content__head
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            カテゴリー一覧
        %li
          = link_to "#" do
            ブランド一覧
    .footer__contents__content
      .footer__contents__content__head
        ヘルプ&ガイド
      %ul
        %li
          = link_to "#" do
            FURIMAガイド
        %li
          = link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            お知らせ
  .footer__logo
    = link_to "#" do
      = image_tag "logo-white.png", class:"image", alt:"logo"
  .footer__name
    ©︎ FURIMA

app/views/items/_indexHeader.html.haml
.header
  .header__inner
    .header__inner__main
      .header__inner__main__icon
        = link_to root_path do
          = image_tag "logo.png", class:"image", alt:"logo"
      .header__inner__main__search
        .header__inner__main__search__form
          = form_with url: "a", local: true, method: :get, class: "header__inner__main__search__form__input" do |form|#f5f5f5
            .header__inner__main__search__form__input__box
              = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-input"
            .header__inner__main__search__form__btn
              = link_to "#" do
                = image_tag "icon-search 1.png", class:"image", alt:"logo"
    .header__inner__nav
      .header__inner__nav__left
        .header__inner__nav__left__category
          %ul.menu
            %li
              = link_to "#" do
                カテゴリー
              %ul.sub-menu-nav
                %li
                  = link_to "#" do
                    レディース
                    %ul
                      %li
                        = link_to "#" do
                          トップス
                          %ul
                            %li
                              = link_to "#" do
                                Tシャツ
                      %li
                        = link_to "#" do
                          ジャケット
                          %ul
                            %li
                              = link_to "#" do
                                ダウンジャケット
                      %li
                        = link_to "#" do
                          パンツ
                          %ul
                            %li
                              = link_to "#" do
                                デニム
                %li
                  = link_to "#" do
                    メンズ
                    %ul
                      %li
                        = link_to "#" do
                          トップス
                          %ul
                            %li
                              = link_to "#" do
                                Tシャツ
                      %li
                        = link_to "#" do
                          ジャケット
                          %ul
                            %li
                              = link_to "#" do
                                ダウンジャケット
                      %li
                        = link_to "#" do
                          パンツ
                          %ul
                            %li
                              = link_to "#" do
                                デニム
                %li
                  = link_to "#" do
                    ベビー・キッズ
                    %ul
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
                      %li
                        = link_to "#" do
                          洋服
                          %ul
                            %li
                              = link_to "#" do
                                洋服
        .header__inner__nav__left__brand
          = link_to "#" do
            ブランド
      .header__inner__nav__right
        - if user_signed_in?
          .header__inner__nav__right__login
            = link_to user_path(current_user) do
              マイページ
          .header__inner__nav__right__new
            = link_to destroy_user_session_path, method: :delete do
              ログアウト
        - else
          .header__inner__nav__right__login
            = link_to new_user_session_path do
              ログイン
          .header__inner__nav__right__new
            = link_to new_user_registration_path do
              新規会員登録

app/views/items/_indexMain.html.haml
.main
  .main__main-visual
    .main__main-visual__content
      .main__main-visual__content__sub-title
        人生を変えるフリマアプリ
      .main__main-visual__content__text
        FURIMAは誰でも簡単に誰でも簡単に出品・購入購入できる
        %br
        フリマアプリです
      .main__main-visual__content__btn
        .main__main-visual__content__btn__app
          = link_to "#" do
            = image_tag "App.svg", class:"image", alt:"logo"
        .main__main-visual__content__btn__google
          = link_to "#" do
            = image_tag "google.png", class:"image", alt:"logo"
  .main__top-introduction
    .main__top-introduction__sub-title
      FURIMAが選ばれる3つの理由
    .main__top-introduction__lists
      .main__top-introduction__lists__list
        .main__top-introduction__lists__list__pict
          .main__top-introduction__lists__list__pict__num
            1
          = image_tag "pict-reason-01.jpg", class:"image", alt:"logo"
        .main__top-introduction__lists__list__text
          %span 3分
          ですぐに出品
        .main__top-introduction__lists__list__description
          スマホで入力するだけで簡単に出品できる！
      .main__top-introduction__lists__list
        .main__top-introduction__lists__list__pict
          .main__top-introduction__lists__list__pict__num
            2
          = image_tag "pict-reason-02.jpg", class:"image", alt:"logo"
        .main__top-introduction__lists__list__text
          %span シンプル
          で使いやすい
        .main__top-introduction__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      .main__top-introduction__lists__list-last
        .main__top-introduction__lists__list-last__pict
          .main__top-introduction__lists__list-last__pict__num
            3
          = image_tag "pict-reason-03.jpg", class:"image", alt:"logo"
        .main__top-introduction__lists__list-last__text
          手数料
          %span 業界最安
        .main__top-introduction__lists__list-last__description
          最大3%でお得に出品&購入！
  .main__sub-visual
    .main__sub-visual__inner
      .main__sub-visual__inner__title
        会員数日本一位
      .main__sub-visual__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__sub-visual__inner__btn
        .main__sub-visual__inner__btn__app
          = link_to "#" do
            = image_tag "App.svg", class:"image", alt:"logo"
        .main__sub-visual__inner__btn__google
          = link_to "#" do
            = image_tag "google.png", class:"image", alt:"logo"
  .main__key-features
    .main__key-features__head
      FURIMAの特徴
    .main__key-features__items
      .main__key-features__items__item
        .main__key-features__items__item__img
          = image_tag "icon-01.png", class:"image", alt:"logo"
        .main__key-features__items__item__sub-title
          簡単に売り買いできる
        .main__key-features__items__item__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .main__key-features__items__item
        .main__key-features__items__item__img
          = image_tag "icon-03.png", class:"image", alt:"logo"
        .main__key-features__items__item__sub-title
          売上金は即日振込みに対応
        .main__key-features__items__item__text
          午前９時までに振込みを依頼頂ければ、翌日に指定の口座に入金いたします！
      .main__key-features__items__item
        .main__key-features__items__item__img
          = image_tag "icon-04.png", class:"image", alt:"logo"
        .main__key-features__items__item__sub-title
          様々な支払いに対応
        .main__key-features__items__item__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .main__pickup
    .main__pickup__head
      ピックアップカテゴリー
    .main__pickup__box
      .main__pickup__box__head
        = link_to "#" do
          新規投稿商品 
      .main__pickup__box__lists
        - @items.each do |item|
          .main__pickup__box__lists__list
            = link_to item_path(item.id) do
              .main__pickup__box__lists__list__img
                - item.images.first(1).each do |image|
                  = image_tag image.src.url, width: "220", height: '150'
                    -if item.buyer_id.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner SOLD
                  %p
                    ¥
                    = converting_to_jpy(item.price)


              .main__pickup__box__lists__list__body
                .main__pickup__box__lists__list__body__name
                  = item.name
                .main__pickup__box__lists__list__body__data
                  .main__pickup__box__lists__list__body__data__like
                    = icon('fa', 'star')
                    0
                  .main__pickup__box__lists__list__body__data__edit
                    - if current_user
                      - if current_user.id == item.seller.id
                        = link_to '編集', edit_item_path(item), data: {"turbolinks" => false}
                        = link_to '削除', item_path(item), method: :delete

app/views/items/_negotiation.html.haml
.messages-container
  .message-list
    %ul.messages
      %li.message
        .user-image
          = image_tag "icon-03.png", class:"image", alt:"logo"
          .exhibitor
          -# if文で出品者か出品者じゃないか分けるコードにする
        .message-body
          .user-name
            y.a
          .message-content
            値下げ出来ますか？
            .icon-box
              .icon
                = icon('far', 'clock')
              .a-day-ago
                3日前

      %li.message
        .user-image
          = image_tag "icon-01.png", class:"image", alt:"logo"
          .exhibitor
            出品者
        .message-body
          .user-name
            yuki
          .message-content
            できかねます
            .icon-box
              .icon
                = icon('far', 'clock')
              .a-day-ago
                3日前

app/views/items/_other-items-box.html.haml
.same-category-items-container
  .same-category-items
    .same-category-items__same-category
      = link_to "#" , class: "same-category-item__category-name" do
        その他 （家電・スマホ・カメラ） その他の商品
    .same-category-items__content
      = link_to "#" do
        .same-category-items__content__box
          .same-category-items__content__box__image
            = image_tag "icon-01.png", class:"image", alt:"logo"
          .same-category-items__content__box__description
            .same-category-items__content__box__description__item-name
              あああああああああああああああああああああああああああああああああああああああああ
              .same-category-items-transparent
            .same-category-items__content__box__description__item-price
              .same-category-items__content__box__description__item-price__price
                ¥20,000
              .same-category-items__content__box__description__item-price__like
                .same-category-items__content__box__description__item-price__like__icon
                  = icon('far', 'heart')
                .same-category-items__content__box__description__item-price__like__count
                  22

      = link_to "#" do
        .same-category-items__content__box
          .same-category-items__content__box__image
            = image_tag "icon-01.png", class:"image", alt:"logo"
          .same-category-items__content__box__description
            .same-category-items__content__box__description__item-name
              あああああああああああああああああああああああああああああああああああああああああ
              .same-category-items-transparent
            .same-category-items__content__box__description__item-price
              .same-category-items__content__box__description__item-price__price
                ¥20,000
              .same-category-items__content__box__description__item-price__like
                .same-category-items__content__box__description__item-price__like__icon
                  = icon('far', 'heart')
                .same-category-items__content__box__description__item-price__like__count
                  22

      = link_to "#" do
        .same-category-items__content__box
          .same-category-items__content__box__image
            = image_tag "icon-01.png", class:"image", alt:"logo"
          .same-category-items__content__box__description
            .same-category-items__content__box__description__item-name
              あああああああああああああああああああああああああああああああああああああああああ
              .same-category-items-transparent
            .same-category-items__content__box__description__item-price
              .same-category-items__content__box__description__item-price__price
                ¥20,000
              .same-category-items__content__box__description__item-price__like
                .same-category-items__content__box__description__item-price__like__icon
                  = icon('far', 'heart')
                .same-category-items__content__box__description__item-price__like__count
                  22

      = link_to "#" do
        .same-category-items__content__box
          .same-category-items__content__box__image
            = image_tag "icon-01.png", class:"image", alt:"logo"
          .same-category-items__content__box__description
            .same-category-items__content__box__description__item-name
              あああああああああああああああああああああああああああああああああああああああああ
              .same-category-items-transparent
            .same-category-items__content__box__description__item-price
              .same-category-items__content__box__description__item-price__price
                ¥20,000
              .same-category-items__content__box__description__item-price__like
                .same-category-items__content__box__description__item-price__like__icon
                  = icon('far', 'heart')
                .same-category-items__content__box__description__item-price__like__count
                  22

      = link_to "#" do
        .same-category-items__content__box
          .same-category-items__content__box__image
            = image_tag "icon-01.png", class:"image", alt:"logo"
          .same-category-items__content__box__description
            .same-category-items__content__box__description__item-name
              あああああああああああああああああああああああああああああああああああああああああ
              .same-category-items-transparent
            .same-category-items__content__box__description__item-price
              .same-category-items__content__box__description__item-price__price
                ¥20,000
              .same-category-items__content__box__description__item-price__like
                .same-category-items__content__box__description__item-price__like__icon
                  = icon('far', 'heart')
                .same-category-items__content__box__description__item-price__like__count
                  22

app/views/items/_social-media-box.html.haml
.social-media-container
  .social-medias
    .facebook
      = link_to "https://www.facebook.com/", class: "facebook__btn" do
        = icon('fab', 'facebook-square')
    .twitter
      = link_to "https://twitter.com/", class: "twitter__btn" do
        = icon('fab', 'twitter')
    .line
      = link_to "https://line.me/ja/", class: "line__btn" do
        = icon('fab', 'line')
    .pinterest
      = link_to "hhttps://www.pinterest.jp/", class: "pinterest__btn" do
        = icon('fab', 'pinterest')

app/views/items/create.html.haml
出品完了

app/views/items/index.html.haml
= render "indexHeader"
= render "indexMain"
= render "indexBanner"
= render "indexFooter"
= render "indexBtn"
.contents.row
  - @items.each do |item|
    %p= item.name
    %span.name
      = item.price
    - item.images.each do |image|
      = image_tag image.src.url
    = link_to '編集', edit_item_path(item)
    = link_to '削除', item_path(item), method: :delete